export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SIGN_OUT_CURRENT_USER = 'SIGN_OUT_CURRENT_USER'
export const CREATE_TODO_LIST = 'CREATE_TODO_LIST';
export const FETCH_TODO_LISTS = 'FETCH_TODO_LISTS';
export const FETCH_TODO_ITEMS = 'FETCH_TODO_ITEMS';
export const CREATE_TODO_ITEM = 'CREATE_TODO_ITEM';
export const UPDATE_TODO_ITEM_STATUS = 'UPDATE_TODO_ITEM_STATUS';
